### ISSUE TITLE
Button to un-resolve a reported issue

### ISSUE THREAD

**Issue by RobertClarke64** [aidandagnall/lab_monitor_client#41]
**Is your feature request related to a problem? Please describe.**
If a reported issue is marked as resolved by accident, there's currently no way to reverse that, other than re-reporting it.

**Describe the solution you'd like**
A button to move the issue back to new or in-progress.

**Comment by aidandagnall** [comment]
Discussed with Joe, I suggested a single "Move to" button which then would show a list of options (Move to new, in-progress, or closed). He wasn't a big fan, but I think it simplifies the UI a tad. Any thoughts @RobertClarke64 ?

**Comment by aidandagnall** [comment]
Merged in #59
